# Makefile.user
CC = arm-linux-gnueabihf-gcc
CFLAGS := -O2 -Wall -Wextra
TARGET := test_ioctl

all: $(TARGET)

$(TARGET): test_ioctl.o
	$(CC) $(CFLAGS) -o $@ $<	

test_ioctl.o: test_ioctl.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o $(TARGET)
