# Makefile.module za ioctl.c
ARCH          ?= arm
CROSS_COMPILE ?= arm-linux-gnueabihf-
KDIR          ?= /lib/modules/$(shell uname -r)/build

obj-m := ioctl.o

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
